PR_SET_NAME = 15
PR_GET_NAME = 16
PR_GET_ENDIAN = 19
PR_SET_ENDIAN = 20

PR_CONSTANT_NAMES = {
    PR_SET_NAME: "PR_SET_NAME",
    PR_GET_NAME: "PR_GET_NAME",
    PR_GET_ENDIAN: "PR_GET_ENDIAN",
    PR_SET_ENDIAN: "PR_SET_ENDIAN",
}